[source]
type = "N2C"
address = ["Unix", "/ipc/node.socket"]
magic = "testnet"

[sink]
type = "Webhook"
url = "http://localhost:9001/events"
timeout = 30000
error_policy = "Continue"

[sink.retry_policy]
max_retries = 30
backoff_unit =  5000
backoff_factor = 2
max_backoff = 100000